name: Main Push
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile && (cd ios && pod install)
